sudo: required

language: node_js

node_js:
  - "7.8.0"

services:
  - docker

env:
  - DOCKER_IMAGE=chiswicked/node-microservice

install:
  - docker build -t $DOCKER_IMAGE .

script:
  - docker run $DOCKER_IMAGE test

after_success:
  - CI_ENV=`bash <(curl -s https://codecov.io/env)`
  - docker run $CI_ENV -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN $DOCKER_IMAGE coverage:travis -s
  - ./bin/push-docker-image `bash ./bin/package-version`
