sudo: required

language: node_js

node_js:
  - "7.8.0"

services:
  - docker

env:
  - DOCKER_IMAGE=chiswicked/node-microservice

install:
  - docker build -t $DOCKER_IMAGE .

script:
  - docker run $DOCKER_IMAGE test

after_success:
  - CC_REPORT_ENV=`bash <(curl -s https://codecov.io/env)` -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN -e CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
  - docker run $CC_REPORT_ENV $DOCKER_IMAGE coverage:travis -s
  - ./bin/push-docker-image `bash ./bin/package-version`
